https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_conf_send_independant.json
Start Fetching '5n4pr_conf_send_independant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_independant_config.json'
Done  Fetching '5n4pr_conf_send_independant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_independant_config.json'
Start Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Done  Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Start Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Done  Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: 
SUCCESS: stop_containers
SUCCESS: reset_nodes_data
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS:




Error executing command: nanomock start && nanomock init_wallets
Error: INFO: Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
INFO:nanomock.internal.utils:Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
SUCCESS: start_containers
SUCCESS:nanomock.internal.utils:start_containers
INFO: WALLET 5F0B50A5EB30F65FD64E6B7FBB583C49B9F2146A3A50FE77DA11B3017A8391C9 CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p
INFO: WALLET 046D578518D50E25E3A697F89A73A1C37A772A36BDFAF0FBB85887C0414B05DE CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub
INFO: WALLET 1EC96CC663B16A49E1D0DABCD3B9A7923F3964EB6EA33C4CD63071DC334EFA65 CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6
INFO: WALLET 7F05773DCBC06F3D1917CB03C48D7213E9CEFD2EC7526D0AFD93F507BDCD3148 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h
INFO: WALLET A3F0FAD16A6593FEDE415A721B25DAB698D3D440899DE1E722EA4C7A5E5F42FD CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8
SUCCESS: ['WALLET 5F0B50A5EB30F65FD64E6B7FBB583C49B9F2146A3A50FE77DA11B3017A8391C9 CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p', 'WALLET 046D578518D50E25E3A697F89A73A1C37A772A36BDFAF0FBB85887C0414B05DE CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub', 'WALLET 1EC96CC663B16A49E1D0DABCD3B9A7923F3964EB6EA33C4CD63071DC334EFA65 CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6', 'WALLET 7F05773DCBC06F3D1917CB03C48D7213E9CEFD2EC7526D0AFD93F507BDCD3148 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h', 'WALLET A3F0FAD16A6593FEDE415A721B25DAB698D3D440899DE1E722EA4C7A5E5F42FD CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8']
.............{'success': False, 'published': False, 'balance_raw': '', 'amount_raw': '0', 'hash': None, 'block': {}, 'subtype': 'receive', 'account_data': {'account': '', 'private': '', 'source_seed': None, 'source_index': None}, 'error': "argument of type 'NoneType' is not iterable"}
DEBUG 1 unconfirmed blocks! e.g. None
..Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 535, in create_block
    if "balance" in source_account_info:
TypeError: argument of type 'NoneType' is not iterable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/threaded_command_mixin.py", line 25, in _execute_command_sequence
    self.command_instance.execute_another_command(command_config)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 35, in publish_create
    asyncio.run(test_case.run())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 120, in run
    await self._generate_and_confirm_block(seed_index)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 110, in _generate_and_confirm_block
    await self.ba_l.assert_blocks_confirmed_wait(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 114, in assert_blocks_confirmed_wait
    confirmed_blocks = await self._blocks_confirmed(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 84, in _blocks_confirmed
    block_info = await self._fetch_block_info(block_hash)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 51, in _fetch_block_info
    return await self.nano_rpc_default.block_info(block_hash,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 472, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 499, in process_payloads
    async with session.post(self.url, json=payloads[0]) as response:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
