186856a04be7e9340e3e5e8b19a8367258e0298d: Pulling from gr0v1ty/nano-node
9cb31e2e37ea: Pulling fs layer
9374902b9f74: Pulling fs layer
2386bc0617e8: Pulling fs layer
8333c60e8d9c: Pulling fs layer
ff35928be7a6: Pulling fs layer
0eed63578a6c: Pulling fs layer
511ed7f6751a: Pulling fs layer
4ff1053465b4: Pulling fs layer
4f4fb700ef54: Pulling fs layer
4d2ef32fa326: Pulling fs layer
7b2197972363: Pulling fs layer
511ed7f6751a: Waiting
4ff1053465b4: Waiting
4f4fb700ef54: Waiting
4d2ef32fa326: Waiting
7b2197972363: Waiting
8333c60e8d9c: Waiting
ff35928be7a6: Waiting
0eed63578a6c: Waiting
9374902b9f74: Download complete
8333c60e8d9c: Verifying Checksum
8333c60e8d9c: Download complete
9cb31e2e37ea: Verifying Checksum
9cb31e2e37ea: Download complete
ff35928be7a6: Verifying Checksum
ff35928be7a6: Download complete
0eed63578a6c: Verifying Checksum
0eed63578a6c: Download complete
4ff1053465b4: Download complete
511ed7f6751a: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
4d2ef32fa326: Verifying Checksum
4d2ef32fa326: Download complete
7b2197972363: Verifying Checksum
7b2197972363: Download complete
9cb31e2e37ea: Pull complete
9374902b9f74: Pull complete
2386bc0617e8: Verifying Checksum
2386bc0617e8: Download complete
2386bc0617e8: Pull complete
8333c60e8d9c: Pull complete
ff35928be7a6: Pull complete
0eed63578a6c: Pull complete
511ed7f6751a: Pull complete
4ff1053465b4: Pull complete
4f4fb700ef54: Pull complete
4d2ef32fa326: Pull complete
7b2197972363: Pull complete
Digest: sha256:91dba4432150286d6257b5819e66df51cf1463e1061057531ed2f97a04796d49
Status: Downloaded newer image for gr0v1ty/nano-node:186856a04be7e9340e3e5e8b19a8367258e0298d
docker.io/gr0v1ty/nano-node:186856a04be7e9340e3e5e8b19a8367258e0298d
https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_conf_change_dependant.json
Start Fetching '5n4pr_conf_change_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_change_dependant_config.json'
Done  Fetching '5n4pr_conf_change_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_change_dependant_config.json'
Start Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Done  Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Start Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Done  Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
SUCCESS: stop_containers completed with None result.
SUCCESS: reset_nodes_data completed with None result.
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
INFO: Log level : default
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
Error executing command: nanomock start && nanomock init_wallets
Error: WARNING: ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4']
INFO: Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
SUCCESS: start_containers completed with None result.
WARNING: ['nl_genesis']
WARNING: ['nl_pr1']
WARNING: ['nl_pr2']
WARNING: ['nl_pr3']
WARNING: ['nl_pr4']
INFO: Nodes ['nl_genesis'] reachable
INFO: Nodes ['nl_pr2'] reachable
INFO: Nodes ['nl_pr3'] reachable
INFO: Nodes ['nl_pr1'] reachable
INFO: Nodes ['nl_pr4'] reachable
INFO: WALLET EA19250A475D0D20D337EB294614493C7CC6F27BF9B6CD69568FB3FBA8F65749 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h
INFO: WALLET D31FE80ED3F390CFA35074A31072B419BD83E4E4283007564B33D1F53DE43AF0 CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub
INFO: WALLET BE3AF589CFB021A4C7DA1B3A56945F5EEDE3269C8C224014F2A578F43B2B78E4 CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/nanomock", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 58, in main
    asyncio.run(main_async(args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 54, in main_async
    await manager.execute_command(args.command, args.nodes, args.payload)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 544, in execute_command
    await command_func(**filtered_command_args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 57, in async_wrapper
    result = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 404, in init_wallets
    await asyncio.gather(*(process_node(node_name) for node_name in node_names))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 398, in process_node
    await init_blocks.create_node_wallet(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/nl_initialise.py", line 202, in create_node_wallet
    wallet = await node_rpc.wallet_create(seed=seed)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 73, in wallet_create
    return await self.nanorpc.wallet_create(seed=seed)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 318, in wallet_create
    return await self.rpc.wallet_create(seed=seed)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 92, in _retry_on_exception
    return await coroutine(*args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 108, in _request
    async with session.post(self.url, json=payloads[0], headers=self.headers) as response:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 1360, in __aenter__
    self._resp: _RetType = await self._coro
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 690, in _request
    await resp.start(conn)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/streams.py", line 644, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
nanorpc.versions.v25_1
nanorpc.versions.v26_0
nanorpc.versions.v26_1
.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/threaded_command_mixin.py", line 26, in _execute_command_sequence
    self.command_instance.execute_another_command(command_config)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 35, in publish_create
    asyncio.run(test_case.run())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 73, in run
    await self._generate_and_confirm_block(seed_index)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 59, in _generate_and_confirm_block
    res = await self.bg_l.blockgen_single_change(source_seed=self.source_seed,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_generator.py", line 56, in blockgen_single_change
    return await self.nano_rpc_default.create_change_block(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 172, in create_change_block
    return await self.get_block_result(block,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 354, in get_block_result
    publish = await self._try_publish_block(block, start_time, exit_after_s)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 388, in _try_publish_block
    publish = await self.process(block["block"], json_block=True)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 58, in process
    return await self.nanorpc.process(block, force=force, subtype=subtype, json_block=json_block, async_=async_)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 200, in process
    return await self.rpc.process(block, force=force, subtype=subtype, json_block=json_block, async_=async_)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 92, in _retry_on_exception
    return await coroutine(*args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 108, in _request
    async with session.post(self.url, json=payloads[0], headers=self.headers) as response:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 1360, in __aenter__
    self._resp: _RetType = await self._coro
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 690, in _request
    await resp.start(conn)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1059, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/streams.py", line 644, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
