34735f71bf6676b227d76be444a662e9707e9873: Pulling from gr0v1ty/nano-node
7646c8da3324: Already exists
60347c499641: Pulling fs layer
2a7e0531d0b8: Pulling fs layer
ef242dee4e63: Pulling fs layer
8a1c63a8f66a: Pulling fs layer
aaa549191e75: Pulling fs layer
0d3675869fc8: Pulling fs layer
ceb319087966: Pulling fs layer
4f4fb700ef54: Pulling fs layer
5d58dc54e94f: Pulling fs layer
f1c201f7213d: Pulling fs layer
0d3675869fc8: Waiting
ceb319087966: Waiting
4f4fb700ef54: Waiting
5d58dc54e94f: Waiting
f1c201f7213d: Waiting
8a1c63a8f66a: Waiting
aaa549191e75: Waiting
60347c499641: Download complete
60347c499641: Pull complete
8a1c63a8f66a: Verifying Checksum
8a1c63a8f66a: Download complete
ef242dee4e63: Verifying Checksum
ef242dee4e63: Download complete
aaa549191e75: Download complete
0d3675869fc8: Download complete
ceb319087966: Verifying Checksum
ceb319087966: Download complete
4f4fb700ef54: Download complete
5d58dc54e94f: Verifying Checksum
5d58dc54e94f: Download complete
f1c201f7213d: Verifying Checksum
f1c201f7213d: Download complete
2a7e0531d0b8: Verifying Checksum
2a7e0531d0b8: Download complete
2a7e0531d0b8: Pull complete
ef242dee4e63: Pull complete
8a1c63a8f66a: Pull complete
aaa549191e75: Pull complete
0d3675869fc8: Pull complete
ceb319087966: Pull complete
4f4fb700ef54: Pull complete
5d58dc54e94f: Pull complete
f1c201f7213d: Pull complete
Digest: sha256:a3678507016c8b0d77c79612a068536c6e438be5445fab3a45ce4aca0588fbe9
Status: Downloaded newer image for gr0v1ty/nano-node:34735f71bf6676b227d76be444a662e9707e9873
docker.io/gr0v1ty/nano-node:34735f71bf6676b227d76be444a662e9707e9873
https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_rocks_10k_change.json
Start Fetching '5n4pr_rocks_10k_change_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_change_config.json'
Done  Fetching '5n4pr_rocks_10k_change_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_change_config.json'
Start Fetching '5n4pr_bucket_rounds_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket_rounds_short.json'
Done  Fetching '5n4pr_bucket_rounds_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket_rounds_short.json'
Start Fetching '5n4pr_buckets_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_buckets_rocksdb.tar.gz'
Done  Fetching '5n4pr_buckets_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_buckets_rocksdb.tar.gz'
Start Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Done  Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Start Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Done  Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
SUCCESS: stop_containers completed with None result.
SUCCESS: reset_nodes_data completed with None result.
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
Error executing command: nanomock start && nanomock init_wallets
Error: WARNING: ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4']
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/nanomock", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 58, in main
    asyncio.run(main_async(args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 54, in main_async
    await manager.execute_command(args.command, args.nodes, args.payload)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 506, in execute_command
    await command_func(**filtered_command_args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 57, in async_wrapper
    result = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 436, in start_containers
    await self._wait_for_rpc_availability(nodes)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 275, in _wait_for_rpc_availability
    raise ValueError(
ValueError: TIMEOUT: RPCs not reachable for nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4']
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
[Errno 111] Connection refusedException in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 30, in start_logger
    asyncio.run(nni.start_loggers(logger_params, sink_params))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/node_interaction.py", line 16, in start_loggers
    await logger_manager.start_logging()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 45, in start_logging
    async for logger, storages in self.create_loggers():
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 41, in create_loggers
    yield await self.create_logger_and_storages(current_params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 22, in create_logger_and_storages
    logger = await LoggerFactory.create_logger(self.logger_type,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/factories/logger_factory.py", line 21, in create_logger
    return await builder.build()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/builders.py", line 44, in build
    await logger.async_init()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 31, in async_init
    self.count_start, self.cemented_start = await self._get_block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 40, in _get_block_count
    block_count = await self.nanorpc.block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 37, in block_count
    return await self.nanorpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 50, in block_count
    return await self.rpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 95, in _retry_on_exception
    raise MaxRetriesExceededError(
nanorpc.client_dynamic.MaxRetriesExceededError: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]

Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
