3ebe2fbfb874a98293830844727a1fb4ea429d96: Pulling from gr0v1ty/nano-node
7646c8da3324: Already exists
a9806c002de7: Pulling fs layer
d495ab728933: Pulling fs layer
a8fce45cff32: Pulling fs layer
9d0ad0c32784: Pulling fs layer
db3fba217e45: Pulling fs layer
07904a71a638: Pulling fs layer
4ee5139a7855: Pulling fs layer
4f4fb700ef54: Pulling fs layer
dfafe6d38523: Pulling fs layer
e0b57d487fc2: Pulling fs layer
9d0ad0c32784: Waiting
db3fba217e45: Waiting
07904a71a638: Waiting
4ee5139a7855: Waiting
e0b57d487fc2: Waiting
4f4fb700ef54: Waiting
dfafe6d38523: Waiting
a9806c002de7: Verifying Checksum
a9806c002de7: Download complete
9d0ad0c32784: Verifying Checksum
9d0ad0c32784: Download complete
db3fba217e45: Verifying Checksum
db3fba217e45: Download complete
a8fce45cff32: Verifying Checksum
a8fce45cff32: Download complete
a9806c002de7: Pull complete
07904a71a638: Download complete
4f4fb700ef54: Download complete
dfafe6d38523: Verifying Checksum
dfafe6d38523: Download complete
e0b57d487fc2: Verifying Checksum
e0b57d487fc2: Download complete
4ee5139a7855: Verifying Checksum
4ee5139a7855: Download complete
d495ab728933: Verifying Checksum
d495ab728933: Download complete
d495ab728933: Pull complete
a8fce45cff32: Pull complete
9d0ad0c32784: Pull complete
db3fba217e45: Pull complete
07904a71a638: Pull complete
4ee5139a7855: Pull complete
4f4fb700ef54: Pull complete
dfafe6d38523: Pull complete
e0b57d487fc2: Pull complete
Digest: sha256:693577389c4f671f3504b0f0c5b6a186eb6d17a86d33abc6d213869300fc4d00
Status: Downloaded newer image for gr0v1ty/nano-node:3ebe2fbfb874a98293830844727a1fb4ea429d96
docker.io/gr0v1ty/nano-node:3ebe2fbfb874a98293830844727a1fb4ea429d96
https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_rocks_10k_change.json
Start Fetching '5n4pr_rocks_10k_change_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_change_config.json'
Done  Fetching '5n4pr_rocks_10k_change_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_change_config.json'
Start Fetching '5n4pr_bucket_rounds_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket_rounds_short.json'
Done  Fetching '5n4pr_bucket_rounds_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket_rounds_short.json'
Start Fetching '5n4pr_buckets_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_buckets_rocksdb.tar.gz'
Done  Fetching '5n4pr_buckets_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_buckets_rocksdb.tar.gz'
Start Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Done  Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Start Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Done  Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
SUCCESS: stop_containers completed with None result.
SUCCESS: reset_nodes_data completed with None result.
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
Error executing command: nanomock start && nanomock init_wallets
Error: WARNING: ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4']
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: [Errno 104] Connection reset by peer
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45101 not yet reachable for node nl_pr1: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
WARNING: RPC http://172.17.0.1:45103 not yet reachable for node nl_pr3: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45103 ssl:default [Connect call failed ('172.17.0.1', 45103)]
WARNING: RPC http://172.17.0.1:45100 not yet reachable for node nl_genesis: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45100 ssl:default [Connect call failed ('172.17.0.1', 45100)]
WARNING: RPC http://172.17.0.1:45102 not yet reachable for node nl_pr2: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45102 ssl:default [Connect call failed ('172.17.0.1', 45102)]
WARNING: RPC http://172.17.0.1:45104 not yet reachable for node nl_pr4: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45104 ssl:default [Connect call failed ('172.17.0.1', 45104)]
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/nanomock", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 58, in main
    asyncio.run(main_async(args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 54, in main_async
    await manager.execute_command(args.command, args.nodes, args.payload)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 506, in execute_command
    await command_func(**filtered_command_args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 57, in async_wrapper
    result = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 436, in start_containers
    await self._wait_for_rpc_availability(nodes)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 275, in _wait_for_rpc_availability
    raise ValueError(
ValueError: TIMEOUT: RPCs not reachable for nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4']
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 30, in start_logger
    asyncio.run(nni.start_loggers(logger_params, sink_params))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/node_interaction.py", line 16, in start_loggers
    await logger_manager.start_logging()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 45, in start_logging
    async for logger, storages in self.create_loggers():
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 41, in create_loggers
    yield await self.create_logger_and_storages(current_params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 22, in create_logger_and_storages
    logger = await LoggerFactory.create_logger(self.logger_type,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/factories/logger_factory.py", line 21, in create_logger
    return await builder.build()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/builders.py", line 44, in build
    await logger.async_init()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 31, in async_init
    self.count_start, self.cemented_start = await self._get_block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 40, in _get_block_count
    block_count = await self.nanorpc.block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 37, in block_count
    return await self.nanorpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 50, in block_count
    return await self.rpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 95, in _retry_on_exception
    raise MaxRetriesExceededError(
nanorpc.client_dynamic.MaxRetriesExceededError: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
