https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_conf_send_dependant.json
Start Fetching '5n4pr_conf_send_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_dependant_config.json'
Done  Fetching '5n4pr_conf_send_dependant_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_conf_send_dependant_config.json'
Start Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Done  Fetching '5n4pr_bucket0-1-88-90-100_10kaccs.ldb' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_bucket0-1-88-90-100_10kaccs.ldb'
Start Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Done  Fetching 'default_5n4pr.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/default_5n4pr.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: 
SUCCESS: stop_containers
SUCCESS: reset_nodes_data
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS:




Error executing command: nanomock start && nanomock init_wallets
Error: INFO: Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
INFO:nanomock.internal.utils:Nodes ['nl_genesis', 'nl_pr1', 'nl_pr2', 'nl_pr3', 'nl_pr4'] reachable
SUCCESS: start_containers
SUCCESS:nanomock.internal.utils:start_containers
INFO: WALLET 55B1C12BE3B6AF7925374C5197B6B4ACA1668D56ABDACBC58215C4E2F5594BDB CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p
INFO: WALLET 8BEF85CE44341F49C5C7C3EAF56640BFA8BA9674C66389EEC19F0437805C3EFD CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub
INFO: WALLET BAA8930C55D376DFBD85DDDED2A2711A40EB03E0E2776D138165A5A541983BEA CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6
INFO: WALLET DE7E7DE14056174D3936AD026E89D21B27453128800E64E45EE2E8792C560618 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h
INFO: WALLET 3AB5AD5DF27282A5314EF4D213343745EC4DF1D46A4D8BEC239781F050284495 CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8
SUCCESS: ['WALLET 55B1C12BE3B6AF7925374C5197B6B4ACA1668D56ABDACBC58215C4E2F5594BDB CREATED FOR nl_genesis WITH ACCOUNT nano_1fzwxb8tkmrp8o66xz7tcx65rm57bxdmpitw39ecomiwpjh89zxj33juzt6p', 'WALLET 8BEF85CE44341F49C5C7C3EAF56640BFA8BA9674C66389EEC19F0437805C3EFD CREATED FOR nl_pr1 WITH ACCOUNT nano_1ge7edbt774uw7z8exomwiu19rd14io1nocyin5jwpiit3133p9eaaxn74ub', 'WALLET BAA8930C55D376DFBD85DDDED2A2711A40EB03E0E2776D138165A5A541983BEA CREATED FOR nl_pr2 WITH ACCOUNT nano_3sz3bi6mpeg5jipr1up3hotxde6gxum8jotr55rzbu9run8e3wxjq1rod9a6', 'WALLET DE7E7DE14056174D3936AD026E89D21B27453128800E64E45EE2E8792C560618 CREATED FOR nl_pr3 WITH ACCOUNT nano_3z93fykzixk7uoswh8fmx7ezefdo7d78xy8sykarpf7mtqi1w4tpg7ejn18h', 'WALLET 3AB5AD5DF27282A5314EF4D213343745EC4DF1D46A4D8BEC239781F050284495 CREATED FOR nl_pr4 WITH ACCOUNT nano_137xfpc4ynmzj3rsf3nej6mzz33n3f7boj6jqsnxpgqw88oh8utqcq7nska8']
..........DEBUG 1 unconfirmed blocks! e.g. 584F44869A513A3E189EE22989333300D1268EE20C5335D98A64969498BB2893
.DEBUG 2 unconfirmed blocks! e.g. 03009B20754C09205D17D2B5898BB8452FC927FB6831DD9A7EA115BB19784F0E
.DEBUG 2 unconfirmed blocks! e.g. AAD61BAB48AE2F6B1431ABA4C765C9547EDC97A80E6B296BCE170504FFA3834A
.DEBUG 2 unconfirmed blocks! e.g. 009C1BE33DC251954EA5FFEAD0B3FAD65800A3247C0699649B2A96A5527C3B2F
.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/threaded_command_mixin.py", line 25, in _execute_command_sequence
    self.command_instance.execute_another_command(command_config)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 35, in publish_create
    asyncio.run(test_case.run())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 120, in run
    await self._generate_and_confirm_block(seed_index)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/test_case.py", line 110, in _generate_and_confirm_block
    await self.ba_l.assert_blocks_confirmed_wait(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 114, in assert_blocks_confirmed_wait
    confirmed_blocks = await self._blocks_confirmed(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 84, in _blocks_confirmed
    block_info = await self._fetch_block_info(block_hash)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/publisher/block_asserts.py", line 51, in _fetch_block_info
    return await self.nano_rpc_default.block_info(block_hash,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 472, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/src/nano_rpc.py", line 499, in process_payloads
    async with session.post(self.url, json=payloads[0]) as response:
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
