fa9180fd190f323d28e71c477a42ab1cb44c8ce5: Pulling from gr0v1ty/nano-node
7646c8da3324: Already exists
b414938e0148: Pulling fs layer
eff757a2898a: Pulling fs layer
14b826a6fb5a: Pulling fs layer
888853d5f5e9: Pulling fs layer
e26a3aa27f22: Pulling fs layer
0366427627bb: Pulling fs layer
d59400f5e543: Pulling fs layer
4f4fb700ef54: Pulling fs layer
fd03e9307c6e: Pulling fs layer
4eb5bff74973: Pulling fs layer
e26a3aa27f22: Waiting
0366427627bb: Waiting
d59400f5e543: Waiting
4f4fb700ef54: Waiting
fd03e9307c6e: Waiting
4eb5bff74973: Waiting
888853d5f5e9: Waiting
b414938e0148: Verifying Checksum
b414938e0148: Download complete
b414938e0148: Pull complete
888853d5f5e9: Verifying Checksum
888853d5f5e9: Download complete
14b826a6fb5a: Verifying Checksum
14b826a6fb5a: Download complete
e26a3aa27f22: Verifying Checksum
e26a3aa27f22: Download complete
0366427627bb: Verifying Checksum
0366427627bb: Download complete
d59400f5e543: Verifying Checksum
d59400f5e543: Download complete
4f4fb700ef54: Download complete
fd03e9307c6e: Verifying Checksum
fd03e9307c6e: Download complete
4eb5bff74973: Verifying Checksum
4eb5bff74973: Download complete
eff757a2898a: Verifying Checksum
eff757a2898a: Download complete
eff757a2898a: Pull complete
14b826a6fb5a: Pull complete
888853d5f5e9: Pull complete
e26a3aa27f22: Pull complete
0366427627bb: Pull complete
d59400f5e543: Pull complete
4f4fb700ef54: Pull complete
fd03e9307c6e: Pull complete
4eb5bff74973: Pull complete
Digest: sha256:ccac3b3337267cc4a1967d537cccb551dab29636bfb69769cb4dafe82f1f2604
Status: Downloaded newer image for gr0v1ty/nano-node:fa9180fd190f323d28e71c477a42ab1cb44c8ce5
docker.io/gr0v1ty/nano-node:fa9180fd190f323d28e71c477a42ab1cb44c8ce5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 49, in execute_another_command
    another_command.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/command.py", line 41, in execute
    self.mixin.execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/command/mixins/python_command_mixin.py", line 40, in execute
    method(**filtered_variables)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/pycmd.py", line 30, in start_logger
    asyncio.run(nni.start_loggers(logger_params, sink_params))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/node_interaction.py", line 16, in start_loggers
    await logger_manager.start_logging()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 45, in start_logging
    async for logger, storages in self.create_loggers():
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 41, in create_loggers
    yield await self.create_logger_and_storages(current_params)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/logger_manager.py", line 22, in create_logger_and_storages
    logger = await LoggerFactory.create_logger(self.logger_type,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/factories/logger_factory.py", line 21, in create_logger
    return await builder.build()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/builders.py", line 44, in build
    await logger.async_init()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 31, in async_init
    self.count_start, self.cemented_start = await self._get_block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanolab/loggers/sources/rpc_logger.py", line 40, in _get_block_count
    block_count = await self.nanorpc.block_count()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/modules/nl_rpc.py", line 37, in block_count
    return await self.nanorpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client.py", line 50, in block_count
    return await self.rpc.block_count(include_cemented=include_cemented)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 33, in method
    return await self.process_payloads([payload])
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 119, in process_payloads
    return await self._request_with_retry(self._request, payloads)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 101, in _request_with_retry
    return await self._retry_on_exception(coroutine,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanorpc/client_dynamic.py", line 95, in _retry_on_exception
    raise MaxRetriesExceededError(
nanorpc.client_dynamic.MaxRetriesExceededError: All 1 retries exhausted for _request. Last error: Cannot connect to host 172.17.0.1:45101 ssl:default [Connect call failed ('172.17.0.1', 45101)]
https://api.github.com/repos/gr0vity-dev/nanolab-configs/contents/quick_testing/5n4pr_rocks_10k_bintree.json
Start Fetching '5n4pr_rocks_10k_bintree_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_bintree_config.json'
Done  Fetching '5n4pr_rocks_10k_bintree_config.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/5n4pr_rocks_10k_bintree_config.json'
Start Fetching '5n4pr_100k_bintree_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_100k_bintree_short.json'
Done  Fetching '5n4pr_100k_bintree_short.json' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_100k_bintree_short.json'
Start Fetching '5n4pr_init_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_init_rocksdb.tar.gz'
Done  Fetching '5n4pr_init_rocksdb.tar.gz' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_init_rocksdb.tar.gz'
Start Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Done  Fetching '5n4pr_quicktesting_config.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/5n4pr_quicktesting_config.toml'
Start Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Done  Fetching 'config-node_5n4pr_spam_buffer_rocks.toml' to '/home/runner/work/nano-node-builder/nano-node-builder/testcases/downloads/config-node_5n4pr_spam_buffer_rocks.toml'
Error executing command: nanomock create && nanomock reset
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-node.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
SUCCESS: stop_containers completed with None result.
SUCCESS: reset_nodes_data completed with None result.
The network 'nl_nano-local' already exists.
Error executing command: nanomock create
Error: INFO: nanomock data has been copied to your current working directory.
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
WARNING: No config-rpc.toml found. minimal version was created
SUCCESS: Docker Compose file created at /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml
SUCCESS: None
SUCCESS: init_containers completed with None result.
Error executing command: nanomock start && nanomock init_wallets
Error: ERROR: Command failed: docker-compose -f /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml -p nanomock up -d
ERROR: Error output: Creating volume "nanomock_nl_default_volume" with default driver
Creating nl_genesis ... 
Creating nl_pr4     ... 
Creating nl_pr2     ... 
Creating nl_pr1     ... 
Creating nl_pr3     ... 
Creating nl_pr2     ... done
Creating nl_pr2_exporter ... 
Creating nl_genesis      ... done
Creating nl_genesis_exporter ... 
Creating nl_pr1              ... done
Creating nl_pr1_exporter     ... 
Creating nl_pr3              ... done
Creating nl_pr4              ... done
Creating nl_pr3_exporter     ... 
Creating nl_pr4_exporter     ... 
Creating nl_pr2_exporter     ... error

ERROR: for nl_pr2_exporter  Cannot start service nl_pr2_exporter: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown
Creating nl_genesis_exporter ... error

ERROR: for nl_genesis_exporter  Cannot start service nl_genesis_exporter: failed to join PID namespace: Container 036b9c91dab2baa20558ca7293b14d38d00dfc104bf398c8d50d600f099e96d1 is restarting, wait until the container is running
Creating nl_pr1_exporter     ... error

ERROR: for nl_pr1_exporter  Cannot start service nl_pr1_exporter: failed to join PID namespace: Container bfb07516768be4df96c61fe754b73a7ae47a49f22dfb8a081e79476be17b8c28 is restarting, wait until the container is running
Creating nl_pr3_exporter     ... error

ERROR: for nl_pr3_exporter  Cannot start service nl_pr3_exporter: failed to join PID namespace: Container 69739db80df0e4e7d4056c564581d9d97afc4e11d82e83e4d3fc8b6e185b6b80 is restarting, wait until the container is running
Creating nl_pr4_exporter     ... error

ERROR: for nl_pr4_exporter  Cannot start service nl_pr4_exporter: failed to join PID namespace: Container 28cbc05e3fe94ffc1aa1b394a1069c14cdcef10b4870ad791fdc45ecbeced6ec is restarting, wait until the container is running

ERROR: for nl_pr2_exporter  Cannot start service nl_pr2_exporter: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF: unknown

ERROR: for nl_genesis_exporter  Cannot start service nl_genesis_exporter: failed to join PID namespace: Container 036b9c91dab2baa20558ca7293b14d38d00dfc104bf398c8d50d600f099e96d1 is restarting, wait until the container is running

ERROR: for nl_pr1_exporter  Cannot start service nl_pr1_exporter: failed to join PID namespace: Container bfb07516768be4df96c61fe754b73a7ae47a49f22dfb8a081e79476be17b8c28 is restarting, wait until the container is running

ERROR: for nl_pr3_exporter  Cannot start service nl_pr3_exporter: failed to join PID namespace: Container 69739db80df0e4e7d4056c564581d9d97afc4e11d82e83e4d3fc8b6e185b6b80 is restarting, wait until the container is running

ERROR: for nl_pr4_exporter  Cannot start service nl_pr4_exporter: failed to join PID namespace: Container 28cbc05e3fe94ffc1aa1b394a1069c14cdcef10b4870ad791fdc45ecbeced6ec is restarting, wait until the container is running
Encountered errors while bringing up the project.

ERROR: Return code: 1
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 198, in subprocess_run_capture_output
    result = subprocess.run(cmd,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'docker-compose -f /home/runner/work/nano-node-builder/nano-node-builder/nano_nodes/docker-compose.yml -p nanomock up -d' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/nanomock", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 58, in main
    asyncio.run(main_async(args))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/main.py", line 54, in main_async
    await manager.execute_command(args.command, args.nodes, args.payload)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 506, in execute_command
    await command_func(**filtered_command_args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 57, in async_wrapper
    result = await func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/nanomock_manager.py", line 435, in start_containers
    self.docker_interface.compose_start(nodes)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/docker/mixin.py", line 56, in compose_start
    return self._run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/docker/mixin.py", line 33, in _run_command
    subprocess_run_capture_output(base_command)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nanomock/internal/utils.py", line 209, in subprocess_run_capture_output
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: <exception str() failed>
Connecting to [::ffff:172.17.0.1]:44100
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44101
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44102
timed out
Connecting to [::ffff:172.17.0.1]:44103
[Errno 111] Connection refused
Connecting to [::ffff:172.17.0.1]:44104
[Errno 111] Connection refused
